spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTHEN2_CLIENT_ID}
            client-secret: ${OAUTHEN2_CLIENT_SECRET}

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://discovery.vothanhtuyen.id.vn/eureka/}
    register-with-eureka: true
    fetch-registry: true