spring:
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URI}
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
  config:
    import: configserver:

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI}
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8081